# Set addAssignees to 'author' to set the PR creator as the assignee.
addAssignees: author

# Set to true to add assignees to pull requests
addReviewers: true

# A list of reviewers to be added to pull requests (GitHub user name)
reviewers:
  - YoshihitoAso
  - purplesmoke05

# A number of reviewers added to the pull request
# Set 0 to add all the reviewers (default: 0)
numberOfReviewers: 0

runOnDraft: true
