version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
    - dependency-name: "*"
      dependency-type: "direct"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
    - dependency-name: "*"
      dependency-type: "direct"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
    - dependency-name: "*"
      dependency-type: "direct"
