repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.4
    hooks:
      - id: ruff-format
        name: ruff-format
        entry: make format
        language_version: python3.11
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.2.5
          - prettier-plugin-solidity@1.3.1
        args:
          - --plugin=prettier-plugin-solidity
        types:
          - solidity