networks:
    default: development
    development:
        gas_price: 0
        cmd_settings:
            port: 8545
            evm_version: berlin
compiler:
    evm_version: berlin
    solc:
        version: 0.8.23
dependencies:
    OpenZeppelin/openzeppelin-contracts@4.9.3
