networks:
    default: development
    development:
        gas_price: 0
        cmd_settings:
            port: 8545
            evm_version: byzantium
compiler:
    evm_version: byzantium
dependencies:
    OpenZeppelin/openzeppelin-contracts@4.2.0
