version: "3"

services:
  ganache-cli:
    image: "trufflesuite/ganache-cli:latest"
    ports:
      - "8545:8545"
  ibet-smartcontract:
    build:
      context: .
      dockerfile: ./tests/Dockerfile
    environment:
      APP_ENV: "dev"
    links:
      - ganache-cli:quorum
    depends_on:
      - ganache-cli
