version: "3"

services:
  ganache-cli:
    image: "trufflesuite/ganache:latest"
    ports:
      - "8545:8545"
    command:
      - --host
      - 0.0.0.0
      - -k
      - 'berlin'
      - -g
      - '0'
      - --gasLimit
      - '800000000'
  sc-unit-test:
    build:
      context: .
      dockerfile: ./tests/Dockerfile
    environment:
      TEST_NETWORK: "test_network"
    links:
      - ganache-cli:quorum
    depends_on:
      - ganache-cli
    volumes:
      - ./output:/app/ibet-SmartContract/output
