version: "3"

services:
  ganache-cli:
    image: "trufflesuite/ganache-cli:latest"
    command: ganache-cli --gasPrice 0 --gasLimit 800000000
  ibet-smartcontract:
    build:
      context: .
      dockerfile: ./tests/Dockerfile
    environment:
      TEST_NETWORK: "test_network"
    links:
      - ganache-cli:quorum
    depends_on:
      - ganache-cli
