services:
  sc-unit-test:
    platform: linux/amd64
    build:
      context: .
      dockerfile: tests/Dockerfile
    environment:
      TEST_NETWORK: "test_network"
    volumes:
      - ./output:/app/ibet-SmartContract/output
