name: test
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: docker-compose run ibet-smartcontract
