name: Unit Test
on: [pull_request]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: UnitTest
        uses: actions/checkout@v2
        run: docker-compose run sc-unit-test
      - uses: actions/upload-artifact@v3
        with:
          name: contract-json
          path: build/interfaces
